### ISSUE TITLE
Install script and install documentation are inconsistent

### ISSUE THREAD

**Issue by sdh4** [limatix/databrowse#9]
The script seems to put stuff in /usr/local/databrowse. But the actual files assume they are in /var/www/databrowse. The documentation suggests /home/databrowse. The installation script also drops stuff in /etc, which I don't think would actually be used (?) 

The install instructions suggest python setup.py install with no prefix set. The script sets --prefix=/usr/local by default (which won't work out-of-the-box on RH-based distros)

**Comment by lesthaeghet** [comment]
This script was never intended for use outside of our lab, which is why it isn't mentioned in the documentation.  I will remove it from the repository but leave it in place in the lab to aide in automating deployment (I will actually move it to the internal theme repository and symlink it).

I'm torn on whether or not to provide such a script for actual distribution.  Such a script, if setup correctly, should be able to handle most of the hard work for most Linux environments, but it poses the risk of someone seeing it without reading anything else and "sudo ./install" without even seeing what it does.
